let productsList = [
  {
    id: 0,
    title: "Hand Base Lamp",
    newPrice: 35.0,
    oldPrice: 55.0,
    image: "images/products_images/Image-1.png",
    altImage: "Product Image 1",
    category: "Light",
  },
  {
    id: 1,
    title: "Vintage Chair",
    newPrice: 65.0,
    oldPrice: 95.0,
    image: "images/products_images/Image-2.png",
    altImage: "Product Image 2",
    category: "Chair",
  },
  {
    id: 2,
    title: "Lamp Tool",
    newPrice: 35.0,
    oldPrice: 45.0,
    image: "images/products_images/Image-3.png",
    altImage: "Product Image 3",
    category: "Light",
  },
  {
    id: 3,
    title: "Stylish Chair",
    newPrice: 45.0,
    oldPrice: 55.0,
    image: "images/products_images/Image-4.png",
    altImage: "Product Image 4",
    category: "Chair",
  },
  {
    id: 4,
    title: "Vintage Chair",
    newPrice: 65.0,
    oldPrice: 95.0,
    image: "images/products_images/Image-5.png",
    altImage: "Product Image 5",
    category: "Chair",
  },
  {
    id: 5,
    title: "Stackable Chair",
    newPrice: 87.0,
    oldPrice: 97.0,
    image: "images/products_images/Image-6.png",
    altImage: "Product Image 6",
    category: "Chair",
  },
  {
    id: 6,
    title: "Sofa",
    newPrice: 150.0,
    oldPrice: 250.0,
    image: "images/products_images/Image-7.png",
    altImage: "Product Image 7",
    category: "Sofa",
  },
  {
    id: 7,
    title: "Sofa",
    newPrice: 98.99,
    oldPrice: 120.0,
    image: "images/products_images/Image-8.png",
    altImage: "Product Image 8",
    category: "Sofa",
  },
];

export default productsList;
